http:
  routers:
    superadmin:
      rule: "Host(`admin-oleg.teambuh.ru`)"
      service: superadmin-ui
      entryPoints:
        - websecure
      tls:
        certResolver: le

  services:
    superadmin-ui:
      loadBalancer:
        servers:
          - url: "http://teambuh-master:3000"
